import 'ast/ast.dart';
import 'ast/datamodel/datamode_ast.dart';

class Generator extends Ast {
  Generator(super.dmmf);

  CodeableAst get datamodel => DatamodelAst(this);

  String generate() {
    final StringBuffer code = StringBuffer();
    code.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    code.writeln();
    code.writeln('import \'package:orm/orm.dart\';');
    code.writeln('import \'package:json_annotation/json_annotation.dart\';');
    code.writeln();
    code.writeln('part \'prisma_generated.g.dart\';');
    code.writeln();
    code.writeln('//'.padRight(80, '*'));
    code.writeln('// This file was generated by Prisma ORM');
    code.writeln('// GitHub: https://github.com/odroe/prisma');
    code.writeln('//'.padRight(80, '*'));
    code.writeln();
    code.writeln(datamodel.codeString);

    return code.toString();
  }
}
