name: prisma_flutter_example
description: "Demo using Prisma ORM in Flutter"
publish_to: "none"
version: 1.0.0+1

resolution: workspace
environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  orm:
    path: ../../packages/orm
  orm_flutter:
    path: ../../packages/orm_flutter
  path_provider: ^2.1.5
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - prisma/migrations/
    - prisma/migrations/20240528135435_init/
