name: orm_flutter_android
description: "Dynamic library implementation library for Prisma Dart and Flutter integration on Android platform."
homepage: https://prisma.pub

resolution: workspace
version: 0.0.3

funding:
  - https://github.com/sponsors/medz
  - https://opencollective.com/openodroe

environment:
  sdk: ^3.5.0
  flutter: ">=3.3.0"

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
